name: Build and Deploy Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Download Latest Awesome repo README
        run: curl https://raw.githubusercontent.com/osmosis-labs/awesome/main/README.md > awesome/README.md

      - name: Install and Build 🔧 # This will create version inside the 'build' folder.
        run: |
          npm install
          npm run build
          
      - name: Deploy to Vercel 
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID}} #Required 
          working-directory: .vuepress/dist
    
      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .vuepress/dist
